version: '3'

networks:
  traefik_network:
    external:
      name: personal-site-network
  default:
    driver: bridge

services:
  personal-site:
    container_name: personal-site
    image: personal-site:latest
    ports:
      - '3003:3003'
    depends_on:
      - personal-site-postgresql
    env_file:
      - .env.prod
    networks:
      - personal-site-network
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.personal-site-rtr.entrypoints=https"
      - "traefik.http.routers.personal-site-rtr.rule=Host(`$PUBLICDOMAIN`)"
      - "traefik.http.routers.personal-site-rtr.tls.certresolver=dns-cloudflare" # added to fix certificate issue
      ## Middlewares
      - "traefik.http.routers.personal-site-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.personal-site-rtr.service=personal-site-svc"
      - "traefik.http.services.personal-site-svc.loadbalancer.server.port=3003"

  personal-site-postgresql:
    container_name: personal-site-postgresql
    image: postgres:15.4
    restart: unless-stopped
    networks:
      - personal-site-network
    expose:
      - '5432'
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env.prod

volumes:
  data: